#!/usr/bin/env python3
"""
Database backup script for PostgreSQL
Exports database schema and data to SQL file
"""
import os
import sys
from datetime import datetime
import subprocess

# Database connection details from .env
DB_HOST = "aws-1-eu-central-2.pooler.supabase.com"
DB_PORT = "6543"
DB_USER = "postgres.ozzvnkmlntifpomkadaf"
DB_PASSWORD = "Juliozafran"
DB_NAME = "postgres"

def backup_with_pg_dump():
    """Backup database using pg_dump command"""
    # Create backup directory
    backup_dir = os.path.join(os.path.dirname(__file__), "..", "sql", "backups")
    os.makedirs(backup_dir, exist_ok=True)

    # Generate backup filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_file = os.path.join(backup_dir, f"database_backup_{timestamp}.sql")

    # Set environment variable for password
    env = os.environ.copy()
    env['PGPASSWORD'] = DB_PASSWORD

    # Build pg_dump command
    cmd = [
        'pg_dump',
        '-h', DB_HOST,
        '-p', DB_PORT,
        '-U', DB_USER,
        '-d', DB_NAME,
        '--no-owner',
        '--no-privileges',
        '--clean',
        '--if-exists',
        '-f', backup_file
    ]

    try:
        print(f"Starting database backup to: {backup_file}")
        result = subprocess.run(cmd, env=env, capture_output=True, text=True)

        if result.returncode == 0:
            file_size = os.path.getsize(backup_file)
            print(f"✓ Backup completed successfully!")
            print(f"  File: {backup_file}")
            print(f"  Size: {file_size / 1024:.2f} KB")
            return backup_file
        else:
            print(f"✗ Backup failed with error:")
            print(result.stderr)
            return None
    except FileNotFoundError:
        print("✗ pg_dump not found. Trying alternative method...")
        return None
    except Exception as e:
        print(f"✗ Error during backup: {e}")
        return None

def backup_with_python():
    """Backup database using Python psycopg2"""
    try:
        import psycopg2
        from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
    except ImportError:
        print("✗ psycopg2 not installed. Installing...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "psycopg2-binary"])
        import psycopg2
        from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

    # Create backup directory
    backup_dir = os.path.join(os.path.dirname(__file__), "..", "sql", "backups")
    os.makedirs(backup_dir, exist_ok=True)

    # Generate backup filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_file = os.path.join(backup_dir, f"database_backup_{timestamp}.sql")

    try:
        print(f"Starting database backup to: {backup_file}")

        # Connect to database
        conn = psycopg2.connect(
            host=DB_HOST,
            port=DB_PORT,
            user=DB_USER,
            password=DB_PASSWORD,
            database=DB_NAME
        )
        conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
        cursor = conn.cursor()

        with open(backup_file, 'w') as f:
            # Write header
            f.write(f"-- PostgreSQL Database Backup\n")
            f.write(f"-- Database: {DB_NAME}\n")
            f.write(f"-- Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"-- Generated by Python backup script\n\n")

            # Get all tables
            cursor.execute("""
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_type = 'BASE TABLE'
                ORDER BY table_name
            """)
            tables = cursor.fetchall()

            print(f"Found {len(tables)} tables to backup")

            # Backup each table
            for (table_name,) in tables:
                print(f"  Backing up table: {table_name}")

                # Get table schema
                cursor.execute(f"""
                    SELECT
                        'CREATE TABLE IF NOT EXISTS ' || quote_ident(table_name) || ' (' ||
                        string_agg(
                            quote_ident(column_name) || ' ' ||
                            data_type ||
                            CASE WHEN character_maximum_length IS NOT NULL
                                THEN '(' || character_maximum_length || ')'
                                ELSE ''
                            END ||
                            CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END,
                            ', '
                        ) || ');'
                    FROM information_schema.columns
                    WHERE table_name = %s
                    AND table_schema = 'public'
                    GROUP BY table_name
                """, (table_name,))

                create_stmt = cursor.fetchone()
                if create_stmt:
                    f.write(f"\n-- Table: {table_name}\n")
                    f.write(f"DROP TABLE IF EXISTS {table_name} CASCADE;\n")
                    f.write(create_stmt[0] + "\n\n")

                # Get table data
                cursor.execute(f'SELECT * FROM {table_name}')
                rows = cursor.fetchall()

                if rows:
                    # Get column names
                    cursor.execute(f"""
                        SELECT column_name
                        FROM information_schema.columns
                        WHERE table_name = %s
                        AND table_schema = 'public'
                        ORDER BY ordinal_position
                    """, (table_name,))
                    columns = [col[0] for col in cursor.fetchall()]

                    f.write(f"-- Data for table: {table_name}\n")
                    for row in rows:
                        values = []
                        for val in row:
                            if val is None:
                                values.append('NULL')
                            elif isinstance(val, str):
                                # Escape single quotes
                                escaped = val.replace("'", "''")
                                values.append(f"'{escaped}'")
                            elif isinstance(val, (datetime, )):
                                values.append(f"'{val}'")
                            else:
                                values.append(str(val))

                        cols = ', '.join(columns)
                        vals = ', '.join(values)
                        f.write(f"INSERT INTO {table_name} ({cols}) VALUES ({vals});\n")

                    f.write("\n")

        cursor.close()
        conn.close()

        file_size = os.path.getsize(backup_file)
        print(f"✓ Backup completed successfully!")
        print(f"  File: {backup_file}")
        print(f"  Size: {file_size / 1024:.2f} KB")
        return backup_file

    except Exception as e:
        print(f"✗ Error during backup: {e}")
        import traceback
        traceback.print_exc()
        return None

if __name__ == "__main__":
    print("=" * 60)
    print("PostgreSQL Database Backup Script")
    print("=" * 60)

    # Try pg_dump first, fall back to Python method
    backup_file = backup_with_pg_dump()

    if not backup_file:
        print("\nTrying Python-based backup method...")
        backup_file = backup_with_python()

    if backup_file:
        print("\n" + "=" * 60)
        print("Backup completed successfully!")
        print(f"Location: {backup_file}")
        print("=" * 60)
        sys.exit(0)
    else:
        print("\n" + "=" * 60)
        print("Backup failed!")
        print("=" * 60)
        sys.exit(1)