#!/usr/bin/env python3
"""
Database backup script for PostgreSQL
Exports database schema and data to SQL file
"""
import os
import sys
from dataclasses import dataclass
from datetime import datetime
import subprocess
from pathlib import Path
from urllib.parse import urlparse, unquote

try:
    from dotenv import dotenv_values
except ImportError:
    dotenv_values = None

BASE_DIR = Path(__file__).resolve().parents[1]
BACKUP_DIR = BASE_DIR / "sql" / "backups"


@dataclass(frozen=True)
class DatabaseConfig:
    url: str
    host: str
    port: str
    user: str
    password: str
    database: str


def get_env_files():
    env_files = [BASE_DIR / "backend" / ".env", BASE_DIR / ".env"]
    backend_env_file = os.getenv("BACKEND_ENV_FILE")
    if backend_env_file:
        env_files.insert(0, Path(backend_env_file))
    return env_files


def load_database_url():
    env_url = os.getenv("DATABASE_URL")
    if env_url:
        return env_url.strip()

    if dotenv_values is None:
        raise RuntimeError("DATABASE_URL not found. Install python-dotenv or set it in the environment.")

    for env_path in get_env_files():
        if not env_path.exists():
            continue
        env_url = dotenv_values(env_path).get("DATABASE_URL")
        if env_url:
            return env_url.strip()

    raise RuntimeError("DATABASE_URL not found. Set it in environment or .env file.")


def parse_database_url(database_url: str) -> DatabaseConfig:
    parsed = urlparse(database_url)
    if parsed.scheme not in ("postgresql", "postgres"):
        raise RuntimeError("DATABASE_URL must be a PostgreSQL connection string.")

    return DatabaseConfig(
        url=database_url,
        host=parsed.hostname or "localhost",
        port=str(parsed.port or 5432),
        user=unquote(parsed.username or ""),
        password=unquote(parsed.password or ""),
        database=parsed.path.lstrip("/") or "postgres",
    )


def load_database_config() -> DatabaseConfig:
    return parse_database_url(load_database_url())


def prepare_backup_file():
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return BACKUP_DIR / f"database_backup_{timestamp}.sql"


def backup_with_pg_dump(db_config: DatabaseConfig):
    """Backup database using pg_dump command"""
    backup_file = prepare_backup_file()

    env = os.environ.copy()
    env["PGPASSWORD"] = db_config.password

    cmd = [
        "pg_dump",
        "-h", db_config.host,
        "-p", db_config.port,
        "-U", db_config.user,
        "-d", db_config.database,
        "--no-owner",
        "--no-privileges",
        "--clean",
        "--if-exists",
        "-f", str(backup_file),
    ]

    try:
        print(f"Starting database backup to: {backup_file}")
        result = subprocess.run(cmd, env=env, capture_output=True, text=True)

        if result.returncode == 0:
            file_size = backup_file.stat().st_size
            print(f"✓ Backup completed successfully!")
            print(f"  File: {backup_file}")
            print(f"  Size: {file_size / 1024:.2f} KB")
            return str(backup_file)
        else:
            print(f"✗ Backup failed with error:")
            print(result.stderr)
            return None
    except FileNotFoundError:
        print("✗ pg_dump not found. Trying alternative method...")
        return None
    except Exception as e:
        print(f"✗ Error during backup: {e}")
        return None


def backup_with_python(db_config: DatabaseConfig):
    """Backup database using Python psycopg2"""
    try:
        import psycopg2
        from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
    except ImportError:
        print("✗ psycopg2 not installed. Installing...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "psycopg2-binary"])
        import psycopg2
        from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

    backup_file = prepare_backup_file()

    try:
        print(f"Starting database backup to: {backup_file}")

        conn = psycopg2.connect(db_config.url)
        conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
        cursor = conn.cursor()

        with backup_file.open("w") as f:
            f.write(f"-- PostgreSQL Database Backup\n")
            f.write(f"-- Database: {db_config.database}\n")
            f.write(f"-- Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"-- Generated by Python backup script\n\n")

            cursor.execute("""
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_type = 'BASE TABLE'
                ORDER BY table_name
            """)
            tables = cursor.fetchall()

            print(f"Found {len(tables)} tables to backup")

            # Backup each table
            for (table_name,) in tables:
                print(f"  Backing up table: {table_name}")

                # Get table schema
                cursor.execute(f"""
                    SELECT
                        'CREATE TABLE IF NOT EXISTS ' || quote_ident(table_name) || ' (' ||
                        string_agg(
                            quote_ident(column_name) || ' ' ||
                            data_type ||
                            CASE WHEN character_maximum_length IS NOT NULL
                                THEN '(' || character_maximum_length || ')'
                                ELSE ''
                            END ||
                            CASE WHEN is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END,
                            ', '
                        ) || ');'
                    FROM information_schema.columns
                    WHERE table_name = %s
                    AND table_schema = 'public'
                    GROUP BY table_name
                """, (table_name,))

                create_stmt = cursor.fetchone()
                if create_stmt:
                    f.write(f"\n-- Table: {table_name}\n")
                    f.write(f"DROP TABLE IF EXISTS {table_name} CASCADE;\n")
                    f.write(create_stmt[0] + "\n\n")

                # Get table data
                cursor.execute(f'SELECT * FROM {table_name}')
                rows = cursor.fetchall()

                if rows:
                    # Get column names
                    cursor.execute(f"""
                        SELECT column_name
                        FROM information_schema.columns
                        WHERE table_name = %s
                        AND table_schema = 'public'
                        ORDER BY ordinal_position
                    """, (table_name,))
                    columns = [col[0] for col in cursor.fetchall()]

                    f.write(f"-- Data for table: {table_name}\n")
                    for row in rows:
                        values = []
                        for val in row:
                            if val is None:
                                values.append('NULL')
                            elif isinstance(val, str):
                                # Escape single quotes
                                escaped = val.replace("'", "''")
                                values.append(f"'{escaped}'")
                            elif isinstance(val, (datetime, )):
                                values.append(f"'{val}'")
                            else:
                                values.append(str(val))

                        cols = ', '.join(columns)
                        vals = ', '.join(values)
                        f.write(f"INSERT INTO {table_name} ({cols}) VALUES ({vals});\n")

                    f.write("\n")

        cursor.close()
        conn.close()

        file_size = backup_file.stat().st_size
        print(f"✓ Backup completed successfully!")
        print(f"  File: {backup_file}")
        print(f"  Size: {file_size / 1024:.2f} KB")
        return str(backup_file)

    except Exception as e:
        print(f"✗ Error during backup: {e}")
        import traceback
        traceback.print_exc()
        return None


if __name__ == "__main__":
    print("=" * 60)
    print("PostgreSQL Database Backup Script")
    print("=" * 60)

    try:
        db_config = load_database_config()
    except RuntimeError as exc:
        print(f"✗ {exc}")
        sys.exit(1)

    # Try pg_dump first, fall back to Python method
    backup_file = backup_with_pg_dump(db_config)

    if not backup_file:
        print("\nTrying Python-based backup method...")
        backup_file = backup_with_python(db_config)

    if backup_file:
        print("\n" + "=" * 60)
        print("Backup completed successfully!")
        print(f"Location: {backup_file}")
        print("=" * 60)
        sys.exit(0)
    else:
        print("\n" + "=" * 60)
        print("Backup failed!")
        print("=" * 60)
        sys.exit(1)
